### ISSUE TITLE
Superscript numbers are not appearing correctly.

### ISSUE THREAD

**Issue by prempiyush** [ibm-cloud-docs/ai-openscale#101]
The superscript numbers besides the frameworks are appearing as regular-sized and not like superscripts are supposed to be.

Link: https://cloud.ibm.com/docs/ai-openscale?topic=ai-openscale-frmwrks-wml#frmwrks-wml

**Comment by msochka** [comment]
We're moving the documentation from IBM Cloud to Watson Studio. There is no method for changing the superscript at this time. In the new doc framework we might be able to address this. Superscript is just that, a letter, number, or symbol that is raised above the baseline. It technically, in traditional typography, does not need to be smaller, although many programs and professional typesetting systems now do this, it was not always required. (Think about how it was done on a typewriter.) For this reason, we won't fix this.
