### ISSUE TITLE
Improper links in "Image model examples" section.

### ISSUE THREAD

**Issue by bluemix001** [ibm-cloud-docs/ai-openscale#97]
There are Improper links in this section.
https://cloud.ibm.com/docs/services/ai-openscale?topic=ai-openscale-ie-image&locale=en#ie-image-working-ntbks

-Tutorial on generating an explanation for an image-based model
(https://github.ibm.com/aiopenscale/explainability/blob/master/public/notebooks/demo/image_explanation.ipynb)

-Tutorial on generating an explanation for an image-based binary classifier model
(https://github.ibm.com/aiopenscale/explainability/blob/master/public/notebooks/demo/image_explanation_binary.ipynb)

Seems these are internal github site.  We have to log in with w3id.
Please correct these links.

**Comment by msochka** [comment]
I have pushed this change to staging. It should be available on PROD later today.

Thanks, @bluemix001 for catching this.
