### ISSUE TITLE
Errors in "Working with unstructured text models"

### ISSUE THREAD

**Issue by prempiyush** [ibm-cloud-docs/ai-openscale#99]
Spotted few errors in this documentation:

Step 2 says `Create and deploy your image-based model.` .. It should be text model.

Step 3 says `Configure Watson OpenScale by assigning the APIClient, sbuscribing the asset and scoring the model.` Typo in `subscribing`

Last statement `Fairness and drift metrics are not supported for unstructured (image or text) data types. {: note}` .. The tag `{: note}` looks like residual code.

**Comment by msochka** [comment]
@prempiyush 

Thanks. I made these changes and will close the issue, since they were very straight-forward.
